/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rns.calculadora;

/**
 *
 * @author nzenguele
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipal = new javax.swing.JPanel();
        jPBotoes = new javax.swing.JPanel();
        btnAC = new javax.swing.JButton();
        btnMais_ou_Menos = new javax.swing.JButton();
        btnDivisao = new javax.swing.JButton();
        btnPercentagem = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiplicacao = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnAdicao = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnSubtracao = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxt = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPBotoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAC.setText("AC");
        jPBotoes.add(btnAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        btnMais_ou_Menos.setText("+/-");
        jPBotoes.add(btnMais_ou_Menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 6, -1, -1));

        btnDivisao.setText("/");
        jPBotoes.add(btnDivisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 6, -1, -1));

        btnPercentagem.setText("%");
        jPBotoes.add(btnPercentagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 6, -1, -1));

        btn7.setText("7");
        jPBotoes.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, -1, -1));

        btn8.setText("8");
        jPBotoes.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 41, -1, -1));

        btn9.setText("9");
        jPBotoes.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 41, -1, -1));

        btnMultiplicacao.setText("x");
        jPBotoes.add(btnMultiplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 41, -1, -1));

        btn3.setText("3");
        jPBotoes.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 111, -1, -1));

        btnAdicao.setText("+");
        jPBotoes.add(btnAdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 111, -1, -1));

        btn4.setText("4");
        jPBotoes.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, -1, -1));

        btn5.setText("5");
        jPBotoes.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 76, -1, -1));

        btnSubtracao.setText("-");
        jPBotoes.add(btnSubtracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 76, -1, -1));

        btn6.setText("6");
        jPBotoes.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 76, -1, -1));

        btn1.setText("1");
        jPBotoes.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, -1, -1));

        btn2.setText("2");
        jPBotoes.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 111, -1, -1));

        btnResultado.setText("=");
        jPBotoes.add(btnResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 146, -1, -1));

        btnPonto.setText(",");
        jPBotoes.add(btnPonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 146, -1, -1));

        btn0.setText("0");
        jPBotoes.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 150, -1));

        jScrollPane1.setViewportView(jTxt);

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAdicao;
    private javax.swing.JButton btnDivisao;
    private javax.swing.JButton btnMais_ou_Menos;
    private javax.swing.JButton btnMultiplicacao;
    private javax.swing.JButton btnPercentagem;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSubtracao;
    private javax.swing.JPanel jPBotoes;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTxt;
    // End of variables declaration//GEN-END:variables
}
